"""firstd

Revision ID: e916ae3848ac
Revises: 
Create Date: 2024-10-07 01:12:23.306671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e916ae3848ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Last_usage',
    sa.Column('last_usage_id', sa.Integer(), nullable=False),
    sa.Column('last_usage', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('last_usage_id')
    )
    op.create_table('Statistics',
    sa.Column('statistics_id', sa.Integer(), nullable=False),
    sa.Column('traffic_usage', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('statistics_id')
    )
    op.create_table('main_server',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('server_ip', sa.String(), nullable=True),
    sa.Column('server_protocol', sa.String(), nullable=True),
    sa.Column('server_port', sa.Integer(), nullable=True),
    sa.Column('server_username', sa.String(), nullable=True),
    sa.Column('server_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('server_id')
    )
    op.create_table('user_detail',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('wallet', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.BigInteger(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['user_detail.chat_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('chat_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('financial_report',
    sa.Column('financial_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('id_holder', sa.Integer(), nullable=True),
    sa.Column('payment_getway', sa.String(), nullable=True),
    sa.Column('authority', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('url_callback', sa.String(), nullable=True),
    sa.Column('additional_data', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['user_detail.chat_id'], ),
    sa.PrimaryKeyConstraint('financial_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('main_server_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_server_id'], ['main_server.server_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('user_config',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('user_level', sa.Integer(), nullable=True),
    sa.Column('traffic_notification_percent', sa.Integer(), nullable=True),
    sa.Column('period_notification_day', sa.Integer(), nullable=True),
    sa.Column('get_vpn_free_service', sa.Boolean(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['user_detail.chat_id'], ),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('purchase',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('traffic', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('day_notification_stats', sa.Boolean(), nullable=True),
    sa.Column('traffic_notification_stats', sa.Boolean(), nullable=True),
    sa.Column('subscription_url', sa.String(), nullable=True),
    sa.Column('upgrade_traffic', sa.Integer(), nullable=True),
    sa.Column('upgrade_period', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['user_detail.chat_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    op.drop_table('user_config')
    op.drop_table('product')
    op.drop_table('financial_report')
    op.drop_table('user_detail')
    op.drop_table('main_server')
    op.drop_table('Statistics')
    op.drop_table('Last_usage')
    # ### end Alembic commands ###
